FROM node:16-alpine

RUN mkdir -p /app

WORKDIR /app

COPY . .

RUN npm install

# Expose the port that the Next.js development server will be running on
EXPOSE 3000

# Start the Next.js development server with the "dev" script
CMD ["npm", "run", "dev"]