# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project directory to the working directory
COPY . .

# Expose the port that the Next.js development server will be running on
EXPOSE 3000

# Start the Next.js development server with the "dev" script
CMD ["npm", "run", "dev"]